# Generated by Django 4.0.8 on 2022-12-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(default='menu', max_length=255),
            preserve_default=False,
        ),
    ]
