# Generated by Django 4.0.8 on 2022-12-25 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
